language: java

#services:
#  - docker
#
#before_install:
#  - docker build -t queen21/demo .
#  - docker run -p 8080:8080 queen21/demo

install: "-./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
script: "-jdk_switcher use openjdk11 -export JAVA_HOME=$HOME/openjdk11 - $TRAVIS_BUILD_DIR/install-jdk.sh
  --install openjdk11 --target $JAVA_HOME -./mvnw test -B"
deploy:
  provider: heroku
  api_key: THDSwc4zUklpFLb4H4RuVqKI7GR5zW6W7fi+ZTFgV6cXGLfZiKHEBHQNwsjpgspYiXWbwuhD5Jw5RQ4Z6TqXn+Dl7D+RAXm9896rYVWKVeBaxIslNP9BI+D9i53Bq95BReKPoly+w6wQxkgI+F1QRL+ffLr0lx+mwg9eQIVTRQoFyEqg0F3LQQB3pVNSihEGPpDNo/9C8b/LuyTTE+TCUKp5LzUmC9iIC/DISFyqmD3nVdEm+XCSTF0hhFLAW99kxzM+rPLNb26TL6BM9HdX0ukIXi7FkNCZPQtWgTXaksei9AacX4fkSsUSllxlsbKpAN2m+BO8YJlnLayr4Rd1WF+5CvzZXW+UNWz3w5jUcLP8pdcoVsgRK8Fgnf61ywYABIBts+LNMaP8HY8/6yYW4JpZilpeqUDloObxw4ATC4u0PkI3Z3KEV3w0k/xvKGiUTNfsXmBVRjcsFQNw7HFCyuQ/+6TWV/TBI/UovhkexcHWKZ17QGd16s+2+1Z6kEA3UuYFrk5HqZn5W1nK0izEMhxUtMVndEfPihqO8Y14jKy1xK+12Dh12vHVKtGw/7p4JB5FkU07jGgeFvEbUfUvAkVl8KSkgPddbjv6GNevrtuefGuCHwHMq3MrUCH8h8gT/ZojAqWke+9wN3Zfx7wy0iZ+zXPMsvTYazt56unABPI=
  app:
    master: demo123-staging
    production: demo123-prod
  on: master
jdk: "-openjdk11"
